exclude_paths:
  - spec
  - vendor

detectors:
  UncommunicativeVariableName:
    accept:
      - f
  IrresponsibleModule:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 5
  UtilityFunction:
    exclude:
      - 'Verselicious::Runner#build_config'
