plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4
